# Generated by Django 5.0.7 on 2024-07-19 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imdb_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('avatar_path', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('review_id', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField()),
                ('imdb_review_url', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
