# Generated by Django 5.0.7 on 2024-07-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_avatar_path_alter_reviews_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
