# Generated by Django 5.0.7 on 2024-07-19 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=50)),
                ('quality', models.IntegerField(default=720)),
                ('type', models.CharField(max_length=20)),
                ('official', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('video_id', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
