# Generated by Django 5.0.7 on 2024-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoples',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='known_for_department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='original_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
