# Generated by Django 5.0.7 on 2024-07-19 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('people', '0001_initial'),
        ('trailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('poster_url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('origin_location', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=30)),
                ('imdb_link', models.CharField(max_length=255)),
                ('run_time', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('actors_cast', models.ManyToManyField(blank=True, null=True, related_name='movie_actors', to='people.peoples')),
                ('director', models.ManyToManyField(blank=True, null=True, related_name='movie_director', to='people.peoples')),
                ('genres', models.ManyToManyField(blank=True, null=True, to='genres.genres')),
                ('youtube_trailer', models.ManyToManyField(blank=True, null=True, to='trailers.trailers')),
            ],
        ),
    ]
