# Generated by Django 5.0.7 on 2024-07-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('movies', '0003_movies_status'),
        ('reviews', '0001_initial'),
        ('trailers', '0002_remove_trailers_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='reviews.reviews'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(blank=True, to='genres.genres'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='youtube_trailer',
            field=models.ManyToManyField(blank=True, to='trailers.trailers'),
        ),
    ]
