# Generated by Django 5.0.7 on 2024-08-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movies_reviews_alter_movies_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='backdrop_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
