# Generated by Django 5.0.7 on 2024-07-19 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
