# Generated by Django 5.0.7 on 2024-07-19 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('people', '0001_initial'),
        ('trailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShows',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('imdb_id', models.CharField(max_length=30, unique=True)),
                ('poster_url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('release_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('origin_location', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=30)),
                ('imdb_link', models.CharField(max_length=255)),
                ('seasons', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('actors_cast', models.ManyToManyField(related_name='tv_actor', to='people.peoples')),
                ('director', models.ManyToManyField(related_name='tv_director', to='people.peoples')),
                ('genres', models.ManyToManyField(to='genres.genres')),
                ('youtube_trailer', models.ManyToManyField(to='trailers.trailers')),
            ],
        ),
    ]
