# Generated by Django 5.0.7 on 2024-07-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('tvshows', '0002_alter_tvshows_description_alter_tvshows_imdb_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='reviews.reviews'),
        ),
    ]
