# Generated by Django 5.0.7 on 2024-09-07 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0004_tvshows_backdrop_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('still_path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('episode_number', models.IntegerField(default=0)),
                ('runtime', models.IntegerField(default=0)),
                ('season_number', models.IntegerField(default=0)),
                ('episode_type', models.CharField(blank=True, max_length=50, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tvshows',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
