# Generated by Django 5.0.7 on 2024-09-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0005_episodes_tvshows_episodes_alter_tvshows_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='tv_show_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='tv_show_id', to='tvshows.tvshows'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='tv_show_tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
